#!/bin/bash 
#SBATCH -A g2019003
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 6:00:00
#SBATCH -J nanoporeillumina
#SBATCH --mail-type=ALL
#SBATCH --mail-user Nadia_Hassan.Shamas.1379@student.uu.se

# Load modules
module load bioinfo-tools
module load spades/3.11.1
 spades.py /
    -1 /home/nadia/genome_analysis/data/DNA/Illumina/E745-1.L500_SZAXPI015146-56_1_clean.fq.gz \
    -2 /home/nadia/genome_analysis/data/DNA/SZAXPI015146-56_2_clean.fq.gz \
    --nanopore /home/nadia/genome_analysis/data/DNA/NanoPore/E745_all.fasta.gz \
    -o /home/nadia/genome_analysis/analyses/-k 21,31,41,51,61,71,81 \
    
